travis:
  secure:
    BINSTAR_TOKEN: C6D8brwpiZ9cPbZtP5Pn4gDSal0IPhi9KxLh8i6wudo3u4A7rdI99QtkRamo6wn53SBrJJxuTgC6votkUntSOmJWZRCkp6BxU20e/diNJaoZsICY7edL2GIxKKvoAh6YQ9pUeGchE6VeEz7anxVzxbdf5zaJM8tOPkj4wA9gHEIaKIDOtHn/Dh/MOIpccEO6b7FM93/aCJeE34dUmVRp3YQoaaNq+/Kmro/kk0+lz/DHMIrtifuq1zrLPZ/VxyHtm/bT4t3l+7i2qQF11UshL/ovsAYd1UjQAH1JIHEihR+Z7YgwFsJiHDucjaBbNkdzBqJ2B+jpYcVQ7H4unXV/50+l/IvRvr7DJF2wUJDVhQJbndNv55UYe48n+Ku17XJeFgjNkfgluyZAA+gLOCNesyBsRPS9cimrwQqKXTT8viONVIYnfoB4xt6uEP8IqYF379ibNc8KdGM0Lbcv58kiSCBffVhDC1x+Je3q7eHEc6lGSZX31yAwWSiSbbZXwpTsB5DZ1yapihDoaKDef0HK8NwYR3mHFew84+cZiJ8vSwdCnyOm/CddN1JIjvu/ROdtOKpA9V4E62rrXjTJFJTPOPbuhanvdBbRW4Xgvpv6Ag9IqhqylrM9CFPO8fdKih9WWREkGCK9vgtznp+Amkq4DTBthDgjjqoeH5URPKJ0BaE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: false
